import type {
  NeighborhoodCollection,
  EstablishmentCollection,
  EstablishmentProperties,
  FilterOptions,
  DashboardOverview,
  EquipmentByNeighborhood,
  ServiceSummaryItem,
} from "../../src/types";
import { ESTABLISHMENT_TYPES, LEGAL_NATURES, MANAGEMENT_TYPES } from "../../src/types";

export const mockFilterOptions: FilterOptions = {
  establishment_types: Object.entries(ESTABLISHMENT_TYPES).map(([value, label]) => ({ value, label })),
  legal_natures: Object.entries(LEGAL_NATURES).map(([value, label]) => ({ value, label })),
  management_types: Object.entries(MANAGEMENT_TYPES).map(([value, label]) => ({ value, label })),
  equipment_items: [
    { value: "", label: "Todos os equipamentos" },
    { value: "02", label: "Mamografo" },
    { value: "11", label: "Tomografo" },
  ],
  specialized_services: [
    { value: "", label: "Todos os serviços" },
    { value: "116", label: "Cardiologia" },
    { value: "132", label: "Oncologia" },
  ],
  reference_categories: [
    { value: "", label: "Todas as referências" },
    { value: "hospital_infeccao", label: "Hospital de Infecção" },
    { value: "referencia_cardiovascular", label: "Referência Cardiovascular" },
    { value: "referencia_oncologica", label: "Referência Oncológica" },
    { value: "referencia_trauma", label: "Referência Trauma/Ortopedia" },
    { value: "hospital_ensino", label: "Hospital de Ensino" },
  ],
};

export const mockNeighborhoods: NeighborhoodCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: null,
      properties: {
        id: 1,
        name: "Pituba",
        region_ibge_code: "2",
        region_name: "Nordeste",
        state_ibge_code: "29",
        state_name: "Bahia",
        city_ibge_code: "2927408",
        city_name: "Salvador",
        district_ibge_code: "292740805",
        district_name: "Distrito Sede",
        subdistrict_ibge_code: "29274080501",
        subdistrict_name: "Subdistrito Norte",
        neighborhood_ibge_code: "29274080501001",
        area_km2: 4.2,
        population_total: 50000,
        population_male: 24000,
        population_female: 26000,
        demographic_density: 120.5,
        population_white: 20000,
        population_black: 10000,
        population_brown: 15000,
        population_asian: 800,
        population_indigenous: 200,
        population_0_to_4: 2500,
        population_5_to_9: 2700,
        population_10_to_14: 2800,
        population_15_to_19: 3000,
        population_20_to_24: 3500,
        population_25_to_29: 4000,
        population_30_to_39: 8000,
        population_40_to_49: 7500,
        population_50_to_59: 6500,
        population_60_to_69: 5500,
        population_70_or_more: 4000,
        population_male_white: 9500,
        population_male_black: 4800,
        population_male_asian: 380,
        population_male_brown: 7200,
        population_male_indigenous: 95,
        population_female_white: 10500,
        population_female_black: 5200,
        population_female_asian: 420,
        population_female_brown: 7800,
        population_female_indigenous: 105,
        establishments_count: 8,
        sus_beds_count: 120,
        equipment_count: 15,
      },
    },
    {
      type: "Feature",
      geometry: null,
      properties: {
        id: 2,
        name: "Barra",
        region_ibge_code: "2",
        region_name: "Nordeste",
        state_ibge_code: "29",
        state_name: "Bahia",
        city_ibge_code: "2927408",
        city_name: "Salvador",
        district_ibge_code: "292740805",
        district_name: "Distrito Sede",
        subdistrict_ibge_code: "29274080502",
        subdistrict_name: "Subdistrito Sul",
        neighborhood_ibge_code: "29274080502001",
        area_km2: 2.8,
        population_total: 30000,
        population_male: 14000,
        population_female: 16000,
        demographic_density: 90.0,
        population_white: 12000,
        population_black: 6000,
        population_brown: 9000,
        population_asian: 600,
        population_indigenous: 150,
        population_0_to_4: 1300,
        population_5_to_9: 1400,
        population_10_to_14: 1500,
        population_15_to_19: 1700,
        population_20_to_24: 2000,
        population_25_to_29: 2400,
        population_30_to_39: 4800,
        population_40_to_49: 4500,
        population_50_to_59: 4000,
        population_60_to_69: 3400,
        population_70_or_more: 2500,
        population_male_white: 5700,
        population_male_black: 2900,
        population_male_asian: 280,
        population_male_brown: 4300,
        population_male_indigenous: 70,
        population_female_white: 6300,
        population_female_black: 3100,
        population_female_asian: 320,
        population_female_brown: 4700,
        population_female_indigenous: 80,
        establishments_count: 3,
        sus_beds_count: 40,
        equipment_count: 5,
      },
    },
  ],
};

export const mockEstablishments: EstablishmentCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-38.5, -12.97] },
      properties: {
        id: 10,
        cnes_code: "0000010",
        name: "UBS Pituba",
        fantasy_name: "UBS Pituba",
        display_type: "Centro de Saude/Unidade Basica",
        establishment_type_code: "02",
        legal_nature_code: "1244",
        legal_nature_name: "Prefeitura Municipal",
        management_type: "M",
        management_name: "Municipal",
        address: "Rua das Flores, 10",
        neighborhood_name: "Pituba",
        zip_code: "41810000",
        phone: "71 3333-0001",
        is_sus: true,
        is_active: true,
        neighborhood_id: 1,
        reference_categories: [],
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [-38.51, -12.96] },
      properties: {
        id: 11,
        cnes_code: "0000011",
        name: "Hospital Geral da Barra",
        fantasy_name: null,
        display_type: "Hospital Geral",
        establishment_type_code: "01",
        legal_nature_code: "1023",
        legal_nature_name: "Secretaria Estadual de Saúde",
        management_type: "E",
        management_name: "Estadual",
        address: "Av. Oceânica, 500",
        neighborhood_name: "Barra",
        zip_code: "40170010",
        phone: "71 3333-0002",
        is_sus: true,
        is_active: true,
        neighborhood_id: 2,
        reference_categories: ["Referência Cardiovascular"],
      },
    },
  ],
};

export const mockEstablishmentDetail: EstablishmentProperties = {
  ...mockEstablishments.features[0].properties,
  reference_categories: ["Referência Cardiovascular"],
  equipments: [
    { code: "02", name: "Mamografo", quantity_existing: 2, quantity_in_use: 1, available_sus: true },
    { code: "11", name: "Tomografo", quantity_existing: 1, quantity_in_use: 1, available_sus: false },
  ],
  services: [
    { code: "116", name: "Cardiologia", classification_code: "001", ambulatorial_sus: true, hospitalar_sus: false },
  ],
  beds: { total_existing: 0, total_sus: 0 },
};

export const mockDashboardOverview: DashboardOverview = {
  establishments: {
    total: 150,
    sus: 120,
    by_type: [
      { code: "02", name: "Centro de Saude/Unidade Basica", count: 60 },
      { code: "01", name: "Hospital Geral", count: 25 },
      { code: "05", name: "Hospital Especializado", count: 15 },
    ],
  },
  equipments: {
    total_equipments: 500,
    sus_equipments: 350,
    by_type: [
      { type: "Mamografo", total: 30 },
      { type: "Tomografo", total: 25 },
    ],
  },
  beds: { total_existing: 2000, total_sus: 1500 },
  neighborhoods: { total: 163, with_data: 160 },
};

export const mockEquipmentByNeighborhood: EquipmentByNeighborhood[] = [
  { neighborhood: "Pituba", total_equipments: 45 },
  { neighborhood: "Barra", total_equipments: 30 },
  { neighborhood: "Brotas", total_equipments: 20 },
];

export const mockServiceSummary: ServiceSummaryItem[] = [
  { code: "116", name: "Cardiologia", establishments_count: 40 },
  { code: "132", name: "Oncologia", establishments_count: 25 },
  { code: "101", name: "ESF", establishments_count: 60 },
];
