name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build web

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: docker compose run --rm --no-deps web bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build web

      - name: Lint code for consistent style
        run: docker compose run --rm --no-deps web bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        env:
          RAILS_ENV: test
        run: docker compose build web

      - name: Start database
        run: docker compose up -d db

      - name: Prepare test database
        env:
          RAILS_ENV: test
        run: docker compose run --rm web bin/rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: docker compose run --rm web bundle exec rspec

  test_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run frontend tests
        run: docker compose run --rm --no-deps frontend sh -c "npm install && npm test"
